Set Deployment Target to 9.0
enfluid/apple-switch-control pull request #39
Opened 2017-01-02 09:55 UTC by andris-zalitis

2017-01-02 10:26 UTC, rudolf-adamkovic requested changes
The project has Deployment Target set to 9.3 with the `SwitchControl` target being set to 9.0. Why? Consider undoing the change and setting the main Deployment Target instead.

2017-01-03 10:31 UTC, andris-zalitis commented
@salutis You're absolutely right!

2017-01-03 21:13 UTC, rudolf-adamkovic approved these changes

2017-01-03 21:13 UTC, merged

2017-01-03 21:13 UTC, salutis commented
@andris-zalitis Good work, thanks!